import {
  PrismaClient,
  AircraftCategory,
  AircraftGeneration,
  Era,
  StealthLevel,
  RadarType,
  ConfidenceLevel,
  WeaponType,
  AircraftStatus,
  MilitaryBranch,
  SitrepCategory,
  DomainType,
  NavalVesselType,
  GroundVehicleCategory,
} from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🛡️ Starting AeroVault Multi-Domain Global Military Defense Seeding...');

  // 1. Clean existing records in reverse dependency order
  await prisma.aircraftDataSource.deleteMany();
  await prisma.aircraftMilestone.deleteMany();
  await prisma.aircraftSnapshot.deleteMany();
  await prisma.aircraftWeapon.deleteMany();
  await prisma.aircraftImage.deleteMany();
  await prisma.dataConflict.deleteMany();
  await prisma.dataChange.deleteMany();
  await prisma.sitrepEvent.deleteMany();
  await prisma.navalVessel.deleteMany();
  await prisma.groundVehicle.deleteMany();
  await prisma.countryForceProfile.deleteMany();
  await prisma.aircraft.deleteMany();
  await prisma.weapon.deleteMany();
  await prisma.dataSource.deleteMany();
  await prisma.nationIntelligence.deleteMany();

  // 2. Seed Data Sources
  const dsJanes = await prisma.dataSource.upsert({
    where: { name: "Jane's Defense & Security 2025" },
    update: {},
    create: {
      name: "Jane's Defense & Security 2025",
      publisher: "IHS Jane's",
      sourceType: 'TIER_2_DEFENSE_JOURNAL',
      reliabilityLevel: 'HIGH',
      url: 'https://www.janes.com',
    },
  });

  const dsDoD = await prisma.dataSource.upsert({
    where: { name: 'US Department of Defense SAR' },
    update: {},
    create: {
      name: 'US Department of Defense SAR',
      publisher: 'United States Government',
      sourceType: 'TIER_1_OFFICIAL',
      reliabilityLevel: 'HIGH',
      url: 'https://www.defense.gov',
    },
  });

  const dsHal = await prisma.dataSource.upsert({
    where: { name: 'HAL & DRDO Annual Technical Whitepaper' },
    update: {},
    create: {
      name: 'HAL & DRDO Annual Technical Whitepaper',
      publisher: 'Ministry of Defence (India)',
      sourceType: 'TIER_1_OFFICIAL',
      reliabilityLevel: 'HIGH',
      url: 'https://hal-india.co.in',
    },
  });

  // 3. Seed Weapons
  const meteor = await prisma.weapon.upsert({
    where: { name: 'Meteor BVRAAM' },
    update: {},
    create: {
      name: 'Meteor BVRAAM',
      type: WeaponType.BVR_AAM,
      manufacturer: 'MBDA',
      originCountry: 'Europe',
      guidance: 'Active Radar Homing / Solid Fuel Ramjet',
      maxRangeKm: 200,
      speedMach: 4.0,
      warheadKg: 25,
      description: 'Beyond-visual-range air-to-air missile with throttleable ducted ramjet engine for unrivaled no-escape zone (>60 km).',
    },
  });

  const brahmos = await prisma.weapon.upsert({
    where: { name: 'BrahMos-A ALCM' },
    update: {},
    create: {
      name: 'BrahMos-A ALCM',
      type: WeaponType.LAND_ATTACK_CRUISE_MISSILE,
      manufacturer: 'BrahMos Aerospace (DRDO / NPO Mashinostroyeniya)',
      originCountry: 'India / Russia',
      guidance: 'Active Radar / GPS / G3OM Indian Satellite Navigation',
      maxRangeKm: 450,
      speedMach: 3.0,
      warheadKg: 300,
      description: 'Air-launched supersonic standoff cruise missile capable of Mach 3 sea-skimming and deep terminal dive.',
    },
  });

  const astra = await prisma.weapon.upsert({
    where: { name: 'Astra Mk1 BVRAAM' },
    update: {},
    create: {
      name: 'Astra Mk1 BVRAAM',
      type: WeaponType.BVR_AAM,
      manufacturer: 'Bharat Dynamics Limited (DRDO)',
      originCountry: 'India',
      guidance: 'Active Radar Homing / Mid-Course Datalink',
      maxRangeKm: 110,
      speedMach: 4.5,
      warheadKg: 15,
      description: 'Indigenous all-weather beyond-visual-range air-to-air missile with smokeless solid propellant.',
    },
  });

  const amraam = await prisma.weapon.upsert({
    where: { name: 'AIM-120D AMRAAM' },
    update: {},
    create: {
      name: 'AIM-120D AMRAAM',
      type: WeaponType.BVR_AAM,
      manufacturer: 'Raytheon Technologies',
      originCountry: 'United States',
      guidance: 'Active Radar Homing / Two-Way GPS Datalink',
      maxRangeKm: 160,
      speedMach: 4.0,
      warheadKg: 20,
      description: 'Premier US BVR air-to-air missile featuring high-off-boresight capability and extended range envelope.',
    },
  });

  const pl15 = await prisma.weapon.upsert({
    where: { name: 'PL-15 BVRAAM' },
    update: {},
    create: {
      name: 'PL-15 BVRAAM',
      type: WeaponType.BVR_AAM,
      manufacturer: 'Aviation Industry Corporation of China (AVIC)',
      originCountry: 'China',
      guidance: 'Active AESA Radar Seeker / Two-Way Datalink',
      maxRangeKm: 200,
      speedMach: 4.5,
      warheadKg: 22,
      description: 'Dual-pulse solid rocket motor active-radar air-to-air missile equipping J-20A and J-16 fighters.',
    },
  });

  // 4. Seed Aircraft
  const su30 = await prisma.aircraft.upsert({
    where: { name: 'Sukhoi Su-30MKI Flanker-H' },
    update: {},
    create: {
      name: 'Sukhoi Su-30MKI Flanker-H',
      commonName: 'Su-30MKI',
      family: 'Su-30 Flanker Family',
      variant: 'Su-30MKI Super Sukhoi',
      block: 'Phase 3 / Super Sukhoi Upgrade',
      manufacturer: 'Hindustan Aeronautics Limited / Sukhoi',
      originCountry: 'Russia / India',
      country: 'India',
      affiliation: 'Indian Air Force',
      militaryBranch: MilitaryBranch.AIR_FORCE,
      serviceStatus: AircraftStatus.ACTIVE,
      category: AircraftCategory.MULTIROLE_FIGHTER,
      generation: AircraftGeneration.GEN_4_5,
      era: Era.MODERN,
      role: 'Air Dominance & Long-Range Strike Fighter',
      secondaryRoles: ['Maritime Strike', 'SEAD', 'Strategic Nuclear Delivery'],
      firstFlightYear: 2000,
      introductionYear: 2002,
      fleetCount: 260,
      activeCount: 260,
      productionCount: 272,
      engineModel: 'AL-31FP Thrust-Vectoring Turbofans',
      engineCount: 2,
      engineType: 'Turbofan',
      hasAfterburner: true,
      thrustAfterburnerKn: 246.0,
      thrustDryKn: 150.0,
      topSpeedMach: 2.0,
      topSpeedKmh: 2120,
      serviceCeilingM: 17300,
      rateOfClimbMs: 300,
      gLimitPositive: 9.0,
      gLimitNegative: -3.0,
      combatRangeKm: 1500,
      ferryRangeKm: 3000,
      emptyWeightKg: 18400,
      maxTakeoffWeightKg: 38800,
      payloadCapacityKg: 8130,
      radarType: RadarType.PESA,
      radarModel: 'N011M Bars PESA (Upgrading to Uttam AESA)',
      radarRangeAirKm: 140,
      hasAesa: false,
      hasIrst: true,
      hasSensorFusion: true,
      hasDatalink: true,
      hasHmd: true,
      stealthLevel: StealthLevel.REDUCED,
      rcsEstimatedM2: 4.0,
      hasRwr: true,
      hasEcm: true,
      hasMaws: true,
      ewScore: 88.0,
      reliabilityScore: 78.0,
      maintenanceHoursPerFlightHour: 18,
      costPerFlightHourUsd: 14500,
      tvrScore: 84.6,
      confidenceLevel: ConfidenceLevel.VERIFIED,
      confidenceScore: 96.0,
      sourceCount: 6,
      description: 'The backbone of the Indian Air Force. Twin-engine, two-seat air superiority fighter featuring 2D thrust-vectoring engines and compatibility with BrahMos-A supersonic cruise missiles.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Sukhoi_Su-30MKI_of_the_Indian_Air_Force_at_Aero_India_2023.jpg/1200px-Sukhoi_Su-30MKI_of_the_Indian_Air_Force_at_Aero_India_2023.jpg',
    },
  });

  await prisma.aircraftWeapon.upsert({
    where: { aircraftId_weaponId: { aircraftId: su30.id, weaponId: brahmos.id } },
    update: {},
    create: { aircraftId: su30.id, weaponId: brahmos.id, maxCapacity: 1 },
  });
  await prisma.aircraftWeapon.upsert({
    where: { aircraftId_weaponId: { aircraftId: su30.id, weaponId: astra.id } },
    update: {},
    create: { aircraftId: su30.id, weaponId: astra.id, maxCapacity: 6 },
  });

  const f22 = await prisma.aircraft.upsert({
    where: { name: 'Lockheed Martin F-22A Raptor' },
    update: {},
    create: {
      name: 'Lockheed Martin F-22A Raptor',
      commonName: 'F-22A Raptor',
      family: 'F-22 Raptor',
      variant: 'F-22A Block 30/35',
      block: 'Increment 3.2B',
      manufacturer: 'Lockheed Martin / Boeing',
      originCountry: 'United States',
      country: 'United States',
      affiliation: 'United States Air Force',
      militaryBranch: MilitaryBranch.AIR_FORCE,
      serviceStatus: AircraftStatus.ACTIVE,
      category: AircraftCategory.AIR_SUPERIORITY,
      generation: AircraftGeneration.GEN_5,
      era: Era.MODERN,
      role: 'Stealth Air Dominance Fighter',
      firstFlightYear: 1997,
      introductionYear: 2005,
      fleetCount: 183,
      activeCount: 183,
      productionCount: 195,
      engineModel: 'Pratt & Whitney F119-PW-100 Supercruising Turbofans',
      engineCount: 2,
      engineType: 'Turbofan',
      hasAfterburner: true,
      thrustAfterburnerKn: 312.0,
      thrustDryKn: 210.0,
      topSpeedMach: 2.25,
      topSpeedKmh: 2414,
      serviceCeilingM: 20000,
      rateOfClimbMs: 350,
      gLimitPositive: 9.5,
      combatRangeKm: 1100,
      ferryRangeKm: 3220,
      emptyWeightKg: 19700,
      maxTakeoffWeightKg: 38000,
      payloadCapacityKg: 9100,
      radarType: RadarType.AESA,
      radarModel: 'AN/APG-77(V)1 AESA',
      radarRangeAirKm: 240,
      hasAesa: true,
      hasSensorFusion: true,
      hasDatalink: true,
      stealthLevel: StealthLevel.VERY_HIGH,
      rcsEstimatedM2: 0.0001,
      hasRwr: true,
      hasEcm: true,
      hasMaws: true,
      ewScore: 98.0,
      reliabilityScore: 74.0,
      tvrScore: 95.8,
      confidenceLevel: ConfidenceLevel.VERIFIED,
      confidenceScore: 98.0,
      sourceCount: 9,
      description: 'The world benchmark for stealth air dominance. Combines extreme low-observability shaping, Mach 1.82 supercruise, and AN/APG-77 AESA radar.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/F-22_Raptor_edit1_%28cropped%29.jpg/1200px-F-22_Raptor_edit1_%28cropped%29.jpg',
    },
  });

  await prisma.aircraftWeapon.upsert({
    where: { aircraftId_weaponId: { aircraftId: f22.id, weaponId: amraam.id } },
    update: {},
    create: { aircraftId: f22.id, weaponId: amraam.id, maxCapacity: 6 },
  });

  // 5. Seed CountryForceProfile Data
  console.log('📊 Seeding CountryForceProfiles...');
  const forceProfiles = [
    {
      country: 'United States',
      countryCode: 'USA',
      flagEmoji: '🇺🇸',
      region: 'North America',
      atlasIndex: 98.5,
      airsIndex: 99.2,
      seasIndex: 97.8,
      armsIndex: 91.4,
      activeTroops: 1328000,
      reserveTroops: 799500,
      paramilitary: 0,
      defenseBudgetUsd: 877.0,
      totalAircraft: 13200,
      totalWarships: 480,
      totalVehicles: 45000,
      nuclearWarheads: 5244,
      aircraftCarriers: 11,
      submarines: 67,
    },
    {
      country: 'China',
      countryCode: 'CHN',
      flagEmoji: '🇨🇳',
      region: 'Asia-Pacific',
      atlasIndex: 92.1,
      airsIndex: 88.4,
      seasIndex: 91.2,
      armsIndex: 94.0,
      activeTroops: 2035000,
      reserveTroops: 510000,
      paramilitary: 660000,
      defenseBudgetUsd: 292.0,
      totalAircraft: 3300,
      totalWarships: 730,
      totalVehicles: 35000,
      nuclearWarheads: 500,
      aircraftCarriers: 3,
      submarines: 61,
    },
    {
      country: 'Russia',
      countryCode: 'RUS',
      flagEmoji: '🇷🇺',
      region: 'Eurasia',
      atlasIndex: 84.3,
      airsIndex: 81.0,
      seasIndex: 78.5,
      armsIndex: 89.2,
      activeTroops: 1320000,
      reserveTroops: 2000000,
      paramilitary: 250000,
      defenseBudgetUsd: 86.4,
      totalAircraft: 4100,
      totalWarships: 590,
      totalVehicles: 30000,
      nuclearWarheads: 5580,
      aircraftCarriers: 1,
      submarines: 58,
    },
    {
      country: 'India',
      countryCode: 'IND',
      flagEmoji: '🇮🇳',
      region: 'South Asia',
      atlasIndex: 81.7,
      airsIndex: 79.5,
      seasIndex: 76.2,
      armsIndex: 85.0,
      activeTroops: 1455000,
      reserveTroops: 1155000,
      paramilitary: 2527000,
      defenseBudgetUsd: 81.4,
      totalAircraft: 2210,
      totalWarships: 295,
      totalVehicles: 12000,
      nuclearWarheads: 172,
      aircraftCarriers: 2,
      submarines: 18,
    },
    {
      country: 'United Kingdom',
      countryCode: 'GBR',
      flagEmoji: '🇬🇧',
      region: 'Europe / NATO',
      atlasIndex: 74.2,
      airsIndex: 72.0,
      seasIndex: 75.8,
      armsIndex: 68.0,
      activeTroops: 184800,
      reserveTroops: 78400,
      paramilitary: 0,
      defenseBudgetUsd: 68.5,
      totalAircraft: 660,
      totalWarships: 75,
      totalVehicles: 1500,
      nuclearWarheads: 225,
      aircraftCarriers: 2,
      submarines: 10,
    },
    {
      country: 'France',
      countryCode: 'FRA',
      flagEmoji: '🇫🇷',
      region: 'Europe / NATO',
      atlasIndex: 73.8,
      airsIndex: 73.5,
      seasIndex: 74.1,
      armsIndex: 69.5,
      activeTroops: 200000,
      reserveTroops: 41000,
      paramilitary: 175000,
      defenseBudgetUsd: 56.6,
      totalAircraft: 970,
      totalWarships: 120,
      totalVehicles: 2500,
      nuclearWarheads: 290,
      aircraftCarriers: 1,
      submarines: 10,
    },
  ];

  for (const fp of forceProfiles) {
    await prisma.countryForceProfile.upsert({
      where: { countryCode: fp.countryCode },
      update: fp,
      create: fp,
    });
  }

  // 6. Seed SitrepEvent Data
  console.log('📡 Seeding SitrepEvents (OSINT Timeline Feed)...');
  const sitrepEvents = [
    {
      eventType: SitrepCategory.DELIVERED,
      domain: DomainType.AIR,
      country: 'India',
      countryCode: 'IND',
      countryFlag: '🇮🇳',
      entityName: 'Tejas Mk1A',
      location: 'Sulur AFS, Tamil Nadu',
      summary: 'Indian Air Force officially accepts delivery of batch Tejas Mk1A fighters fitted with Uttam AESA radar at Sulur AFS.',
      sourceUrl: 'https://mod.gov.in',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2025-02-15'),
    },
    {
      eventType: SitrepCategory.COMMISSIONED,
      domain: DomainType.NAVY,
      country: 'India',
      countryCode: 'IND',
      countryFlag: '🇮🇳',
      entityName: 'INS Arighat',
      location: 'Visakhapatnam Naval Base',
      summary: 'Indian Navy commissions second Arihant-class nuclear ballistic missile submarine (SSBN) INS Arighat into service at Visakhapatnam.',
      sourceUrl: 'https://indiannavy.nic.in',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2024-08-29'),
    },
    {
      eventType: SitrepCategory.RETIRED,
      domain: DomainType.AIR,
      country: 'United States',
      countryCode: 'USA',
      countryFlag: '🇺🇸',
      entityName: 'EC-130H Compass Call',
      location: 'Davis-Monthan AFB, Arizona',
      summary: 'USAF completes final operational retirement flight of EC-130H Compass Call electronic warfare airframe from Davis-Monthan AFB.',
      sourceUrl: 'https://af.mil',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2024-11-10'),
    },
    {
      eventType: SitrepCategory.COMMISSIONED,
      domain: DomainType.NAVY,
      country: 'United States',
      countryCode: 'USA',
      countryFlag: '🇺🇸',
      entityName: 'USS New Jersey (SSN-796)',
      location: 'Naval Weapons Station Earle, NJ',
      summary: 'US Navy commissions Virginia-class fast attack submarine USS New Jersey into the fleet.',
      sourceUrl: 'https://navy.mil',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2024-09-14'),
    },
    {
      eventType: SitrepCategory.DELIVERED,
      domain: DomainType.LAND,
      country: 'India',
      countryCode: 'IND',
      countryFlag: '🇮🇳',
      entityName: 'T-90M Bhishma',
      location: 'Heavy Vehicles Factory (HVF), Avadi',
      summary: 'Indian Army receives upgraded T-90M Bhishma main battle tanks with thermal imaging and localized explosive reactive armor (ERA).',
      sourceUrl: 'https://drdo.gov.in',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2025-01-20'),
    },
    {
      eventType: SitrepCategory.SHOT_DOWN,
      domain: DomainType.AIR,
      country: 'Russia',
      countryCode: 'RUS',
      countryFlag: '🇷🇺',
      entityName: 'Su-34 Fullback',
      location: 'Eastern Operational Theater',
      summary: 'Visual OSINT confirms tactical fighter-bomber loss over eastern operational theater.',
      sourceUrl: 'https://aviation-safety.net',
      confidence: ConfidenceLevel.VERIFIED,
      eventDate: new Date('2024-12-05'),
    },
  ];

  for (const ev of sitrepEvents) {
    await prisma.sitrepEvent.create({ data: ev });
  }

  // 7. Seed NavalVessel Data
  console.log('⚓ Seeding NavalVessels...');
  const navalVessels = [
    {
      name: 'INS Vikrant (IAC-1)',
      shipClass: 'Vikrant-class Aircraft Carrier',
      vesselType: NavalVesselType.AIRCRAFT_CARRIER,
      country: 'India',
      countryCode: 'IND',
      militaryBranch: MilitaryBranch.NAVAL_AVIATION,
      status: AircraftStatus.ACTIVE,
      displacementTons: 45000,
      maxSpeedKnots: 28.0,
      commissionedYear: 2022,
      crewComplement: 1645,
      activeCount: 1,
      originCountry: 'India (Cochin Shipyard)',
      pennantNumber: 'R11',
      radarType: RadarType.AESA,
      hasAesa: true,
      tvrScore: 88.5,
      description: 'Indigenous aircraft carrier operating STOBAR ski-jump ski configurations with MiG-29K, Rafale-M, and MH-60R Seahawk air wings.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/INS_Vikrant_underway_during_sea_trials.jpg/1200px-INS_Vikrant_underway_during_sea_trials.jpg',
    },
    {
      name: 'USS Gerald R. Ford (CVN-78)',
      shipClass: 'Gerald R. Ford-class Supercarrier',
      vesselType: NavalVesselType.AIRCRAFT_CARRIER,
      country: 'United States',
      countryCode: 'USA',
      militaryBranch: MilitaryBranch.NAVAL_AVIATION,
      status: AircraftStatus.ACTIVE,
      displacementTons: 100000,
      maxSpeedKnots: 30.0,
      commissionedYear: 2017,
      crewComplement: 4539,
      activeCount: 1,
      originCountry: 'United States (Huntington Ingalls)',
      pennantNumber: 'CVN-78',
      radarType: RadarType.AESA,
      hasAesa: true,
      tvrScore: 98.4,
      description: 'Premier nuclear-powered supercarrier equipped with Electromagnetic Aircraft Launch System (EMALS), AAG arresting gear, and Dual Band Radar.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/USS_Gerald_R._Ford_%28CVN-78%29_underway_in_the_Atlantic_Ocean_on_8_April_2017_%28170408-N-WJ386-067%29.jpg/1200px-USS_Gerald_R._Ford_%28CVN-78%29_underway_in_the_Atlantic_Ocean_on_8_April_2017_%28170408-N-WJ386-067%29.jpg',
    },
    {
      name: 'INS Surat (D69)',
      shipClass: 'Visakhapatnam-class Guided Missile Destroyer (Project 15B)',
      vesselType: NavalVesselType.GUIDED_MISSILE_DESTROYER,
      country: 'India',
      countryCode: 'IND',
      militaryBranch: MilitaryBranch.NAVAL_AVIATION,
      status: AircraftStatus.ACTIVE,
      displacementTons: 7400,
      maxSpeedKnots: 30.0,
      commissionedYear: 2024,
      crewComplement: 312,
      activeCount: 1,
      originCountry: 'India (Mazagon Dock Shipbuilders)',
      pennantNumber: 'D69',
      radarType: RadarType.AESA,
      hasAesa: true,
      tvrScore: 89.2,
      description: 'Next-generation stealth guided-missile destroyer armed with BrahMos supersonic cruise missiles and Barak-8 long-range surface-to-air missiles.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/INS_Visakhapatnam_%28D66%29.jpg/1200px-INS_Visakhapatnam_%28D66%29.jpg',
    },
  ];

  for (const nv of navalVessels) {
    await prisma.navalVessel.upsert({
      where: { name: nv.name },
      update: nv,
      create: nv,
    });
  }

  // 8. Seed GroundVehicle Data
  console.log('🚜 Seeding GroundVehicles...');
  const groundVehicles = [
    {
      name: 'T-90M Bhishma',
      category: GroundVehicleCategory.MAIN_BATTLE_TANK,
      country: 'India',
      countryCode: 'IND',
      militaryBranch: MilitaryBranch.ARMY_AVIATION,
      status: AircraftStatus.ACTIVE,
      activeCount: 1300,
      reserveCount: 350,
      generation: '3rd Gen MBT',
      mainArmament: '125mm 2A46M-5 Smoothbore Gun (Refleks ATGM capable)',
      enginePowerHp: 1000.0,
      topSpeedKmh: 60.0,
      weightTons: 46.5,
      tvrScore: 84.0,
      description: 'Main battle tank with third-generation composite armor, Kontakt-5 / Relikt explosive reactive armor, and automated fire control with Catherine-FC thermal sight.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/T-90M_Proryv-3_-_Armiya2021-36.jpg/1200px-T-90M_Proryv-3_-_Armiya2021-36.jpg',
    },
    {
      name: 'M1A2 SEPv3 Abrams',
      category: GroundVehicleCategory.MAIN_BATTLE_TANK,
      country: 'United States',
      countryCode: 'USA',
      militaryBranch: MilitaryBranch.ARMY_AVIATION,
      status: AircraftStatus.ACTIVE,
      activeCount: 2500,
      reserveCount: 2000,
      generation: '3rd Gen MBT',
      mainArmament: '120mm M256 Smoothbore Cannon',
      enginePowerHp: 1500.0,
      topSpeedKmh: 67.0,
      weightTons: 66.8,
      tvrScore: 92.5,
      description: 'System Enhancement Package version 3 featuring Trophy Active Protection System (APS), joint tactical datalinks, and depleted uranium composite armor.',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/M1A2_Abrams_SEPv3_tank_in_Grafenwoehr%2C_Germany%2C_2021.jpg/1200px-M1A2_Abrams_SEPv3_tank_in_Grafenwoehr%2C_Germany%2C_2021.jpg',
    },
  ];

  for (const gv of groundVehicles) {
    await prisma.groundVehicle.upsert({
      where: { name: gv.name },
      update: gv,
      create: gv,
    });
  }

  // 9. Seed NationIntelligence
  console.log('🌐 Seeding NationIntelligence Airpower Data...');
  await prisma.nationIntelligence.createMany({
    data: [
      {
        countryName: 'United States',
        countryCode: 'USA',
        flag: '🇺🇸',
        airForceName: 'United States Air Force',
        armyAviationName: 'US Army Aviation Branch',
        navalAviationName: 'US Naval Air Forces',
        globalRanking: 1,
        tvrTotal: 96.4,
        combatPowerScore: 98.2,
        strikeScore: 96.5,
        mobilityScore: 95.0,
        aewcScore: 97.4,
        tankerScore: 99.1,
        uavScore: 96.0,
        navalAirScore: 98.0,
        armyAirScore: 94.5,
        modernizationIndex: 89.2,
        logisticsScore: 94.0,
        forceReadiness: 92.0,
        totalActiveUnits: 5209,
        airForceUnits: 3100,
        armyAviationUnits: 1200,
        navalAviationUnits: 909,
        marineUnits: 450,
        totalFighters: 1950,
        totalBombers: 140,
        totalTransports: 680,
        totalHelicopters: 1450,
        totalUAVs: 480,
        totalAEWC: 32,
        totalTankers: 470,
        totalTrainers: 1100,
        gen5Count: 543,
        gen45Count: 650,
        gen4Count: 757,
        legacyCount: 0,
        primaryStrengths: ['Largest operational 5th-gen stealth fleet', 'Unrivaled aerial tanker force', 'Carrier aviation dominance'],
        primaryLimitations: ['High operating cost per flight hour', 'Pilot training backlog'],
      },
      {
        countryName: 'China',
        countryCode: 'CHN',
        flag: '🇨🇳',
        airForceName: "People's Liberation Army Air Force (PLAAF)",
        armyAviationName: 'PLA Ground Force Aviation',
        navalAviationName: 'PLA Naval Air Force (PLAN-AF)',
        globalRanking: 2,
        tvrTotal: 89.8,
        combatPowerScore: 92.4,
        strikeScore: 89.0,
        mobilityScore: 84.5,
        aewcScore: 91.0,
        tankerScore: 78.0,
        uavScore: 94.0,
        navalAirScore: 86.5,
        armyAirScore: 88.0,
        modernizationIndex: 84.5,
        logisticsScore: 87.0,
        forceReadiness: 88.0,
        totalActiveUnits: 3166,
        airForceUnits: 2200,
        armyAviationUnits: 550,
        navalAviationUnits: 416,
        totalFighters: 1550,
        totalBombers: 120,
        totalTransports: 280,
        totalHelicopters: 820,
        totalUAVs: 350,
        totalAEWC: 35,
        totalTankers: 30,
        totalTrainers: 650,
        gen5Count: 250,
        gen45Count: 600,
        gen4Count: 500,
        legacyCount: 200,
        primaryStrengths: ['Rapid J-20A mass production', 'Long-range PL-15/17 AAMs', 'Extensive UAV development'],
        primaryLimitations: ['Relatively small tanker fleet', 'Limited expeditionary sortie history'],
      },
      {
        countryName: 'India',
        countryCode: 'IND',
        flag: '🇮🇳',
        airForceName: 'Indian Air Force (IAF)',
        armyAviationName: 'Indian Army Aviation Corps',
        navalAviationName: 'Indian Naval Air Arm',
        globalRanking: 4,
        tvrTotal: 81.6,
        combatPowerScore: 84.8,
        strikeScore: 82.0,
        mobilityScore: 81.0,
        aewcScore: 78.0,
        tankerScore: 74.0,
        uavScore: 76.0,
        navalAirScore: 80.0,
        armyAirScore: 78.0,
        modernizationIndex: 76.5,
        logisticsScore: 76.0,
        forceReadiness: 85.0,
        totalActiveUnits: 1645,
        airForceUnits: 1100,
        armyAviationUnits: 340,
        navalAviationUnits: 205,
        totalFighters: 620,
        totalBombers: 0,
        totalTransports: 250,
        totalHelicopters: 520,
        totalUAVs: 110,
        totalAEWC: 6,
        totalTankers: 6,
        totalTrainers: 310,
        gen5Count: 0,
        gen45Count: 296,
        gen4Count: 280,
        legacyCount: 44,
        primaryStrengths: ['High-altitude Himalayan operational mastery', 'Formidable Rafale/Su-30MKI strike pairing', 'Carrier-borne naval aviation'],
        primaryLimitations: ['Fighter squadron deficit against 42-squadron authorization', 'Multi-origin foreign supply chain complexity'],
      },
    ],
  });

  console.log('✅ AeroVault Multi-Domain Global Military Fleet Seeding Complete.');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
